### ISSUE TITLE
Scaling on Mobile

### ISSUE THREAD

**Issue by rolfea** [ianroberts131/visual-algorithms#26]
# Feature
Scaling on Mobile and Smaller Screens 
## Why is this feature being added?
Improve the User Experience by allowing mobile users to enjoy this cool app.

## What should your feature do?
Fix the CSS to respond to mobile dynamically
---
You can reproduce this by popping into Dev Tools (F12 / CMD+ALT+I in chrome) and using the resize feature to mimic mobile dimensions.

**Comment by ianroberts131** [comment]
Yeah this should be pretty high on the list. I think we should move forward with React-Bootstrap.
https://react-bootstrap.github.io/

**Comment by ianroberts131** [comment]
I got this basically there, so I'm going to close this issue. There are a few outstanding items (namely landscape on mobile), but I'll just create separate issues as bugs are found.
